/**
 * Bibliothèque d'exercices sans équipement, répartis en 4 disciplines :
 * endurance, muscu, souplesse, combat. Chaque exercice dure 50 secondes
 * d'effort intense (voir app.js) — la description sert de rappel rapide
 * de la bonne exécution. `difficulty` va de 1 (facile) à 4 (très dur) et
 * sert à la fois pour la jauge affichée sur chaque exercice et pour le
 * score quotidien de l'écran Stats.
 */
const EXERCISES = [
  // ---------------------------------------------------------------------
  // ENDURANCE
  // ---------------------------------------------------------------------
  { id: "jumping-jacks", name: "Jumping jacks", category: "endurance", difficulty: 1,
    description: "Sautez en écartant bras et jambes, puis revenez en position de départ." },
  { id: "montees-genoux", name: "Montées de genoux", category: "endurance", difficulty: 2,
    description: "Courez sur place en montant les genoux le plus haut possible." },
  { id: "talons-fesses", name: "Talons-fesses", category: "endurance", difficulty: 1,
    description: "Courez sur place en amenant les talons vers les fessiers." },
  { id: "mountain-climbers", name: "Mountain climbers", category: "endurance", difficulty: 3,
    description: "En planche, ramenez rapidement les genoux vers la poitrine en alternant." },
  { id: "squats-sautes", name: "Squats sautés", category: "endurance", difficulty: 3,
    description: "Descendez en squat puis explosez vers le haut en sautant." },
  { id: "skaters", name: "Skaters", category: "endurance", difficulty: 3,
    description: "Sautez latéralement d'une jambe sur l'autre façon patineur." },
  { id: "star-jumps", name: "Star jumps", category: "endurance", difficulty: 2,
    description: "Accroupi, sautez en ouvrant bras et jambes en étoile." },
  { id: "corde-a-sauter", name: "Corde à sauter imaginaire", category: "endurance", difficulty: 2,
    description: "Petits sauts rapides sur place en mimant une corde à sauter." },
  { id: "burpees", name: "Burpees", category: "endurance", difficulty: 4,
    description: "Planche, pompe, ramenez les pieds, puis sautez bras tendus vers le ciel." },
  { id: "deplacements-lateraux", name: "Déplacements latéraux", category: "endurance", difficulty: 2,
    description: "Pas chassés rapides de gauche à droite en position basse." },
  { id: "sprint-sur-place", name: "Sprint sur place", category: "endurance", difficulty: 3,
    description: "Courez sur place le plus vite possible, petits appuis rapides." },
  { id: "fentes-sautees", name: "Fentes sautées", category: "endurance", difficulty: 3,
    description: "Alternez les jambes en fente avec un saut à chaque changement." },

  // Difficulté 1 : cardio léger
  { id: "marche-sur-place", name: "Marche sur place", category: "endurance", difficulty: 1,
    description: "Marchez sur place en levant légèrement les genoux, bras relâchés, rythme tranquille." },
  { id: "pas-toucher-talon", name: "Toucher-talons arrière", category: "endurance", difficulty: 1,
    description: "Marchez sur place en amenant chaque talon vers la fesse sans sauter, rythme modéré." },
  { id: "rotation-bras", name: "Moulinets de bras", category: "endurance", difficulty: 1,
    description: "Debout, faites de grands cercles avec les bras vers l'avant puis vers l'arrière en rythme." },
  { id: "pas-chasses-lents", name: "Pas chassés lents", category: "endurance", difficulty: 1,
    description: "Déplacez-vous latéralement à petits pas chassés, rythme tranquille, genoux légèrement fléchis." },
  { id: "montee-genoux-lente", name: "Montées de genoux lentes", category: "endurance", difficulty: 1,
    description: "Levez alternativement chaque genou à hauteur de hanche, sans sauter, rythme contrôlé." },
  { id: "squat-sans-saut", name: "Squat rythmé sans saut", category: "endurance", difficulty: 1,
    description: "Descendez en squat léger puis remontez, sans saut, en rythme continu." },
  { id: "balancement-lateral", name: "Balancement latéral", category: "endurance", difficulty: 1,
    description: "Transférez le poids d'un pied à l'autre en fléchissant légèrement les genoux, bras qui suivent le mouvement." },
  { id: "pas-croises", name: "Pas croisés (grapevine)", category: "endurance", difficulty: 1,
    description: "Déplacez-vous latéralement en croisant un pied devant puis derrière l'autre, rythme modéré." },

  // Difficulté 2 : cardio modéré
  { id: "jumping-jacks-croises", name: "Jumping jacks croisés", category: "endurance", difficulty: 2,
    description: "Sautez en croisant bras et jambes alternativement, comme des ciseaux." },
  { id: "pas-chasses-rapides", name: "Pas chassés rapides", category: "endurance", difficulty: 2,
    description: "Déplacez-vous latéralement à pas chassés rapides sur toute la largeur disponible." },
  { id: "montee-genoux-touche-main", name: "Montées de genoux avec touché de main", category: "endurance", difficulty: 2,
    description: "Levez chaque genou vers la main opposée tendue devant vous, rythme soutenu." },
  { id: "squat-pulse", name: "Squat pulsé", category: "endurance", difficulty: 2,
    description: "Restez en position basse de squat et effectuez de petits pulses vers le bas en rythme." },
  { id: "shuffle-lateral", name: "Shuffle latéral", category: "endurance", difficulty: 2,
    description: "Petits pas rapides d'un côté à l'autre, genoux fléchis, buste légèrement penché en avant." },
  { id: "talons-fesses-rapides", name: "Talons-fesses rapides", category: "endurance", difficulty: 2,
    description: "Courez sur place en amenant rapidement les talons vers les fessiers, rythme soutenu." },

  // Difficulté 3 : cardio intense
  { id: "squat-jump-alterne", name: "Squat jump alterné", category: "endurance", difficulty: 3,
    description: "Sautez en position squat en alternant une jambe légèrement en avant à chaque saut." },
  { id: "burpee-sans-pompe", name: "Burpee sans pompe", category: "endurance", difficulty: 3,
    description: "Descendez en planche, ramenez les pieds vers les mains puis sautez bras tendus, sans marquer la pompe." },
  { id: "sprint-genoux-hauts", name: "Sprint genoux hauts", category: "endurance", difficulty: 3,
    description: "Courez sur place le plus vite possible en montant les genoux très haut." },
  { id: "fentes-alternees-rapides", name: "Fentes alternées rapides", category: "endurance", difficulty: 3,
    description: "Alternez rapidement les jambes en fente avant, sans temps d'arrêt entre chaque changement." },
  { id: "jumping-jacks-amples", name: "Jumping jacks amples", category: "endurance", difficulty: 3,
    description: "Sautez en écartant bras et jambes le plus largement possible, rythme soutenu." },

  // Difficulté 4 : cardio explosif
  { id: "burpee-avec-pompe-saut", name: "Burpee avec pompe et saut", category: "endurance", difficulty: 4,
    description: "Planche, pompe complète, ramenez les pieds puis sautez le plus haut possible bras tendus." },
  { id: "sprint-max", name: "Sprint sur place maximal", category: "endurance", difficulty: 4,
    description: "Courez sur place à vitesse maximale, appuis les plus rapides possible, sans ralentir." },
  { id: "squat-jump-explosif", name: "Squat jump explosif", category: "endurance", difficulty: 4,
    description: "Descendez en squat profond puis sautez le plus haut possible, réception souple, enchîânez sans pause." },
  { id: "mountain-climbers-explosifs", name: "Mountain climbers explosifs", category: "endurance", difficulty: 4,
    description: "En planche, ramenez les genoux vers la poitrine le plus vite possible en alternant." },
  { id: "burpee-star-jump", name: "Burpee star jump", category: "endurance", difficulty: 4,
    description: "Enchîânez un burpee complet puis un star jump à la réception, sans pause." },
  { id: "skater-jump-ample", name: "Skater jump amples", category: "endurance", difficulty: 4,
    description: "Sautez latéralement le plus loin possible d'une jambe sur l'autre, façon patineur de vitesse." },
  { id: "fentes-sautees-max", name: "Fentes sautées explosives", category: "endurance", difficulty: 4,
    description: "Alternez les jambes en fente avec un saut maximal à chaque changement, rythme soutenu." },
  { id: "tuck-jump", name: "Tuck jump", category: "endurance", difficulty: 4,
    description: "Sautez verticalement en ramenant les deux genoux vers la poitrine au sommet du saut." },
  { id: "high-knees-sprint", name: "High knees sprint", category: "endurance", difficulty: 4,
    description: "Sprintez sur place en martelant le sol, genoux à hauteur de hanche, bras qui pompent fort." },

  // ---------------------------------------------------------------------
  // MUSCU
  // ---------------------------------------------------------------------
  { id: "pompes", name: "Pompes", category: "muscu", difficulty: 2,
    description: "Corps aligné, descendez coudes à 45°, puis repoussez le sol." },
  { id: "pompes-diamant", name: "Pompes diamant", category: "muscu", difficulty: 3,
    description: "Mains sous la poitrine en losange, focus triceps." },
  { id: "pompes-piquees", name: "Pompes piquées", category: "muscu", difficulty: 3,
    description: "Fessiers en l'air en V inversé, pliez les coudes vers le sol." },
  { id: "gainage-planche", name: "Gainage planche", category: "muscu", difficulty: 2,
    description: "Appui avant-bras, corps aligné tête-bassin-talons, gainé." },
  { id: "gainage-lateral", name: "Gainage latéral", category: "muscu", difficulty: 2,
    description: "Sur le côté, appui avant-bras, corps aligné, hanche haute." },
  { id: "squats", name: "Squats", category: "muscu", difficulty: 1,
    description: "Pieds largeur bassin, descendez cuisses parallèles au sol." },
  { id: "fentes-avant", name: "Fentes avant", category: "muscu", difficulty: 2,
    description: "Alternez les jambes en fente, genou arrière proche du sol." },
  { id: "superman", name: "Superman", category: "muscu", difficulty: 1,
    description: "Au sol sur le ventre, soulevez bras et jambes simultanément." },
  { id: "crunchs-velo", name: "Crunchs vélo", category: "muscu", difficulty: 2,
    description: "Coude vers le genou opposé en alternant, comme un pédalage." },
  { id: "russian-twists", name: "Russian twists", category: "muscu", difficulty: 2,
    description: "Assis, buste incliné, tournez le buste de chaque côté." },
  { id: "v-ups", name: "V-ups", category: "muscu", difficulty: 3,
    description: "Allongé, levez jambes et buste ensemble pour former un V." },
  { id: "chaise", name: "Chaise", category: "muscu", difficulty: 2,
    description: "Dos au mur, cuisses parallèles au sol, maintenez la position." },
  { id: "hip-thrust", name: "Hip thrust au sol", category: "muscu", difficulty: 1,
    description: "Allongé, genoux pliés, poussez le bassin vers le haut." },
  { id: "dips-triceps", name: "Dips triceps au sol", category: "muscu", difficulty: 2,
    description: "Mains au sol derrière vous, pliez les coudes pour descendre le bassin." },

  // Difficulté 1 : renforcement léger
  { id: "squat-mur", name: "Squat au mur léger", category: "muscu", difficulty: 1,
    description: "Dos au mur, descendez légèrement en squat et maintenez quelques secondes avant de remonter." },
  { id: "gainage-genoux", name: "Gainage planche sur les genoux", category: "muscu", difficulty: 1,
    description: "Appui avant-bras et genoux au sol, corps aligné tête-bassin-genoux, gainé." },
  { id: "releve-bassin", name: "Relevé de bassin", category: "muscu", difficulty: 1,
    description: "Allongé, genoux pliés, soulevez doucement le bassin puis reposez, rythme contrôlé." },
  { id: "extension-dos-douce", name: "Extension du dos douce", category: "muscu", difficulty: 1,
    description: "Allongé sur le ventre, soulevez légèrement la poitrine du sol, mains le long du corps." },
  { id: "fente-statique-legere", name: "Fente statique légère", category: "muscu", difficulty: 1,
    description: "Un pied devant, descendez légèrement le genou arrière sans forcer, dos droit." },
  { id: "crunch-classique", name: "Crunch classique", category: "muscu", difficulty: 1,
    description: "Allongé, genoux pliés, décollez les épaules du sol en contractant les abdominaux." },
  { id: "elevation-mollets", name: "Élévation des mollets", category: "muscu", difficulty: 1,
    description: "Debout, montez sur la pointe des pieds puis redescendez lentement." },

  // Difficulté 2 : renforcement modéré
  { id: "squat-sumo", name: "Squat sumo", category: "muscu", difficulty: 2,
    description: "Pieds très écartés, pointes vers l'extérieur, descendez en squat en gardant le dos droit." },
  { id: "pompes-genoux", name: "Pompes sur les genoux", category: "muscu", difficulty: 2,
    description: "Genoux au sol, mains largeur épaules, descendez la poitrine puis repoussez le sol." },

  // Difficulté 3 : renforcement intense
  { id: "pompes-larges", name: "Pompes prise large", category: "muscu", difficulty: 3,
    description: "Mains bien plus larges que les épaules, descendez la poitrine près du sol puis repoussez." },
  { id: "gainage-planche-longue", name: "Gainage planche longue durée", category: "muscu", difficulty: 3,
    description: "Appui avant-bras, corps aligné et gainé, maintenez la position sans faiblir." },
  { id: "squat-bulgare", name: "Squat bulgare (sans support)", category: "muscu", difficulty: 3,
    description: "Un pied surélevé derrière vous en équilibre, descendez en fente profonde sur la jambe avant." },
  { id: "leg-raise", name: "Relevé de jambes", category: "muscu", difficulty: 3,
    description: "Allongé sur le dos, jambes tendues, montez-les à la verticale puis redescendez sans toucher le sol." },
  { id: "pompes-declinees", name: "Pompes déclinées", category: "muscu", difficulty: 3,
    description: "Pieds surélevés, mains au sol, descendez la poitrine puis repoussez, angle plus difficile." },
  { id: "gainage-lateral-jambe-levee", name: "Gainage latéral jambe levée", category: "muscu", difficulty: 3,
    description: "En gainage latéral, levez la jambe du dessus en maintenant les hanches hautes et alignées." },
  { id: "superman-dynamique", name: "Superman dynamique", category: "muscu", difficulty: 3,
    description: "Allongé sur le ventre, soulevez bras et jambes puis reposez-les en rythme, sans les traîner au sol." },

  // Difficulté 4 : renforcement extrême
  { id: "pistol-squat", name: "Pistol squat assisté", category: "muscu", difficulty: 4,
    description: "Sur une jambe, descendez le plus bas possible en tendant l'autre jambe devant vous, bras en équilibre." },
  { id: "pompes-archer", name: "Pompes archer", category: "muscu", difficulty: 4,
    description: "Mains très écartées, descendez en pliant un bras pendant que l'autre reste tendu, alternez." },
  { id: "planche-bras-leve", name: "Planche avec bras levé", category: "muscu", difficulty: 4,
    description: "En planche avant-bras, levez un bras tendu devant vous en gardant les hanches stables, alternez." },
  { id: "pompes-plyo", name: "Pompes pliométriques", category: "muscu", difficulty: 4,
    description: "Descendez en pompe puis poussez fort pour décoller les mains du sol à la remontée, réceptionnez souplement." },
  { id: "v-ups-croises", name: "V-ups croisés", category: "muscu", difficulty: 4,
    description: "Allongé, levez jambes et buste en croisant la main vers le pied opposé à chaque répétition." },
  { id: "pompes-diamant-piquees", name: "Pompes diamant piquées", category: "muscu", difficulty: 4,
    description: "Fessiers en l'air, mains en losange sous le visage, pliez les coudes vers le bas, très exigeant." },
  { id: "squat-jump-charge", name: "Squat jump chargé", category: "muscu", difficulty: 4,
    description: "Descendez en squat profond puis sautez le plus haut possible, enchîânez immédiatement le squat suivant." },
  { id: "dips-jambes-tendues", name: "Dips triceps jambes tendues", category: "muscu", difficulty: 4,
    description: "Mains au sol derrière vous, jambes tendues devant, descendez profondément le bassin puis repoussez." },
  { id: "planche-jambe-levee", name: "Planche jambe levée", category: "muscu", difficulty: 4,
    description: "En gainage planche, levez une jambe tendue sans casser l'alignement du dos, alternez." },
  { id: "pompes-hindoues", name: "Pompes hindoues", category: "muscu", difficulty: 4,
    description: "Partez fesses hautes, plongez le buste vers l'avant en rasant le sol puis relevez le buste en cambrant, mouvement fluide et exigeant." },

  // ---------------------------------------------------------------------
  // SOUPLESSE
  // ---------------------------------------------------------------------
  { id: "etirement-ischios", name: "Étirement des ischio-jambiers", category: "souplesse", difficulty: 1,
    description: "Jambe tendue devant, penchez le buste vers l'avant, dos droit." },
  { id: "flexion-avant", name: "Flexion assise vers l'avant", category: "souplesse", difficulty: 1,
    description: "Assis jambes tendues, basculez le buste vers l'avant depuis les hanches." },
  { id: "etirement-papillon", name: "Étirement papillon", category: "souplesse", difficulty: 1,
    description: "Assis, plantes de pieds jointes, appuyez doucement les genoux vers le sol." },
  { id: "posture-enfant", name: "Posture de l'enfant", category: "souplesse", difficulty: 1,
    description: "À genoux, asseyez-vous sur les talons, bras tendus devant vous." },
  { id: "chat-vache", name: "Chat-vache", category: "souplesse", difficulty: 1,
    description: "À quatre pattes, alternez dos creusé et dos arrondi au rythme du souffle." },
  { id: "chien-tete-en-bas", name: "Chien tête en bas", category: "souplesse", difficulty: 2,
    description: "Hanches vers le haut et l'arrière, formez un V inversé, talons vers le sol." },
  { id: "etirement-hanche", name: "Étirement fléchisseur de hanche", category: "souplesse", difficulty: 1,
    description: "En fente basse, poussez doucement le bassin vers l'avant." },
  { id: "etirement-quadriceps", name: "Étirement des quadriceps", category: "souplesse", difficulty: 2,
    description: "Debout, ramenez un talon vers la fesse en tenant la cheville." },
  { id: "etirement-fessier", name: "Étirement fessier (figure 4)", category: "souplesse", difficulty: 1,
    description: "Allongé, cheville croisée sur le genou opposé, tirez la cuisse vers vous." },
  { id: "etirement-cobra", name: "Étirement cobra", category: "souplesse", difficulty: 1,
    description: "Allongé sur le ventre, poussez le buste vers le haut, bassin au sol." },
  { id: "genou-poitrine", name: "Genou vers la poitrine", category: "souplesse", difficulty: 1,
    description: "Allongé, ramenez un genou vers la poitrine avec les deux mains." },
  { id: "torsion-assise", name: "Torsion du buste assise", category: "souplesse", difficulty: 1,
    description: "Assis, tournez le buste d'un côté en gardant le dos droit." },
  { id: "etirement-epaules", name: "Étirement épaules et triceps", category: "souplesse", difficulty: 1,
    description: "Bras au-dessus de la tête, coude plié, tirez doucement derrière la nuque." },

  // Adducteurs
  { id: "etirement-grenouille", name: "Étirement grenouille", category: "souplesse", difficulty: 2,
    description: "À quatre pattes, écartez largement les genoux, chevilles alignées avec les genoux. Reculez doucement le bassin vers les talons pour étirer l'intérieur des cuisses." },
  { id: "fente-laterale-cosaque", name: "Fente latérale (Cosaque)", category: "souplesse", difficulty: 3,
    description: "Jambes très écartées, pliez un genou en gardant l'autre jambe tendue, pied à plat. Basculez le poids d'un côté à l'autre pour étirer les adducteurs en dynamique." },
  { id: "grand-ecart-lateral", name: "Grand écart latéral progressif", category: "souplesse", difficulty: 4,
    description: "Jambes écartées au maximum de votre mobilité, mains au sol devant vous, laissez le bassin descendre progressivement pour approfondir l'étirement des adducteurs." },

  // Déplacements animaliers
  { id: "deplacement-ours", name: "Déplacement de l'ours", category: "souplesse", difficulty: 3,
    description: "À quatre pattes, genoux légèrement décollés du sol, avancez en faisant bouger la main et le pied opposés ensemble, dos plat et hanches basses." },
  { id: "deplacement-crabe", name: "Déplacement du crabe", category: "souplesse", difficulty: 3,
    description: "Assis, mains derrière vous, bassin décollé du sol. Déplacez-vous sur les mains et les pieds en gardant les hanches hautes et le dos droit." },
  { id: "deplacement-canard", name: "Déplacement du canard", category: "souplesse", difficulty: 3,
    description: "Descendez en squat profond, talons au sol si possible, et avancez à petits pas en restant bas, genoux vers l'extérieur." },
  { id: "deplacement-lezard", name: "Déplacement du lézard", category: "souplesse", difficulty: 3,
    description: "En fente basse très ouverte, mains au sol à l'intérieur du pied avant, avancez en alternant les côtés comme un lézard qui rampe, hanches proches du sol." },
  { id: "la-chenille", name: "La chenille", category: "souplesse", difficulty: 2,
    description: "Debout, pliez le buste et posez les mains au sol, marchez avec les mains vers l'avant jusqu'à la planche, puis ramenez les pieds vers les mains jambes tendues." },

  // Postures de yoga
  { id: "yoga-guerrier-2", name: "Posture du guerrier II", category: "souplesse", difficulty: 2,
    description: "Jambes écartées, genou avant plié à 90°, bras tendus à l'horizontale. Regard vers la main avant, hanches ouvertes sur le côté, maintenez la position." },
  { id: "yoga-arbre", name: "Posture de l'arbre", category: "souplesse", difficulty: 2,
    description: "En équilibre sur une jambe, posez le pied opposé contre la cheville, le mollet ou la cuisse (jamais sur le genou), mains jointes devant la poitrine." },
  { id: "yoga-pigeon", name: "Posture du pigeon", category: "souplesse", difficulty: 3,
    description: "Genou avant plié devant vous, tibia proche de l'horizontale, jambe arrière tendue derrière. Penchez le buste vers l'avant pour approfondir l'ouverture de hanche." },
  { id: "yoga-pince-debout", name: "Pince debout", category: "souplesse", difficulty: 1,
    description: "Debout, jambes tendues ou légèrement fléchies, laissez le buste tomber vers l'avant, tête relâchée, mains vers le sol ou les tibias." },
  { id: "yoga-corbeau", name: "Posture du corbeau", category: "souplesse", difficulty: 4,
    description: "Accroupi, mains au sol largeur épaules, posez les genoux sur l'arrière des bras et penchez le poids vers l'avant pour décoller les pieds du sol." },
  { id: "yoga-demi-lune", name: "Posture de la demi-lune", category: "souplesse", difficulty: 4,
    description: "En équilibre sur une jambe et une main au sol, levez l'autre jambe et l'autre bras à l'horizontale, corps aligné comme un T." },
  { id: "yoga-charrue", name: "Posture de la charrue", category: "souplesse", difficulty: 3,
    description: "Allongé sur le dos, levez les jambes puis les hanches pour amener les pieds au sol derrière la tête, mains au sol ou soutenant le bas du dos." },

  // Étirements dynamiques
  { id: "balancers-jambe", name: "Balancers de jambe dynamiques", category: "souplesse", difficulty: 2,
    description: "Debout en appui sur un support, balancez une jambe tendue d'avant en arrière puis latéralement, amplitude progressive." },

  // Difficulté 2 (suite)
  { id: "etirement-mollets", name: "Étirement des mollets", category: "souplesse", difficulty: 2,
    description: "Mains au mur, une jambe reculée tendue, talon au sol, penchez-vous doucement vers l'avant." },
  { id: "torsion-couchee", name: "Torsion couchée", category: "souplesse", difficulty: 2,
    description: "Allongé sur le dos, genoux pliés, laissez-les basculer d'un côté en gardant les épaules au sol." },
  { id: "yoga-triangle", name: "Posture du triangle", category: "souplesse", difficulty: 2,
    description: "Jambes écartées, penchez le buste sur le côté en posant la main sur le tibia, autre bras tendu vers le ciel." },

  // Difficulté 3 (suite)
  { id: "arabesque-jambe-tendue", name: "Fente arabesque", category: "souplesse", difficulty: 3,
    description: "Sur une jambe, penchez le buste vers l'avant en tendant l'autre jambe droite derrière vous, bras écartés pour l'équilibre." },
  { id: "fente-profonde-rotation", name: "Fente profonde avec rotation", category: "souplesse", difficulty: 3,
    description: "En fente basse, tournez le buste vers la jambe avant en levant le bras opposé vers le plafond." },
  { id: "yoga-danseur", name: "Posture du danseur", category: "souplesse", difficulty: 3,
    description: "En équilibre sur une jambe, attrapez la cheville arrière et tirez-la doucement vers le haut en penchant le buste." },

  // Difficulté 4 (suite)
  { id: "grand-ecart-facial", name: "Grand écart facial progressif", category: "souplesse", difficulty: 4,
    description: "Une jambe devant, une derrière, glissez progressivement vers le grand écart avant selon votre mobilité." },
  { id: "yoga-scorpion-prep", name: "Posture du scorpion (préparation)", category: "souplesse", difficulty: 4,
    description: "En appui sur les avant-bras, amenez les pieds vers la tête en cambrant le dos, progressivement." },
  { id: "pont-complet", name: "Pont complet", category: "souplesse", difficulty: 4,
    description: "Allongé, mains près des oreilles, poussez pour soulever tout le corps en arche, bras et jambes tendus." },
  { id: "yoga-roue-prep", name: "Préparation à la roue", category: "souplesse", difficulty: 4,
    description: "Depuis le pont, essayez de tendre davantage les bras et les jambes pour approfondir la posture." },
  { id: "deplacement-singe", name: "Déplacement du singe", category: "souplesse", difficulty: 4,
    description: "Accroupi bas, avancez rapidement à quatre pattes façon singe, hanches proches du sol, amplitude maximale." },
  { id: "grand-ecart-avant", name: "Grand écart avant progressif", category: "souplesse", difficulty: 4,
    description: "Une jambe tendue devant, l'autre tendue derrière, laissez le bassin descendre progressivement vers le sol." },
  { id: "yoga-roi-danseur", name: "Posture du roi danseur", category: "souplesse", difficulty: 4,
    description: "En équilibre sur une jambe, attrapez le pied arrière à deux mains et tirez-le vers la tête en cambrant." },

  // ---------------------------------------------------------------------
  // COMBAT
  // ---------------------------------------------------------------------
  // Difficulté 1 : technique et bases au ralenti
  { id: "garde-de-base", name: "Garde de base", category: "combat", difficulty: 1,
    description: "Placez-vous en garde, poings devant le visage, coudes proches du corps, respirez calmement en tenant la position." },
  { id: "jab-lent", name: "Jab au ralenti", category: "combat", difficulty: 1,
    description: "Depuis la garde, lancez des jabs lents et contrôlés en insistant sur la technique et le retour en garde." },
  { id: "pas-en-garde", name: "Déplacements en garde lente", category: "combat", difficulty: 1,
    description: "Avancez et reculez à petits pas depuis la garde, sans jamais croiser les appuis." },
  { id: "rotation-hanches-combat", name: "Rotation des hanches", category: "combat", difficulty: 1,
    description: "Debout, pivotez doucement les hanches d'un côté puis de l'autre pour préparer les frappes rotatives." },
  { id: "genou-lent", name: "Montée de genou lente", category: "combat", difficulty: 1,
    description: "Montez un genou vers le centre lentement et avec contrôle, en gardant l'équilibre, alternez les jambes." },
  { id: "esquive-douce", name: "Esquive douce", category: "combat", difficulty: 1,
    description: "Fléchissez légèrement les jambes pour baisser le corps comme pour esquiver, puis remontez, sans précipitation." },
  { id: "shadow-boxing-lent", name: "Shadow boxing au ralenti", category: "combat", difficulty: 1,
    description: "Enchîânez jab et cross au ralenti en visualisant un adversaire, focus sur la technique." },
  { id: "respiration-combat", name: "Respiration de combat", category: "combat", difficulty: 1,
    description: "En garde, expirez fort à chaque frappe imaginaire lente, travaillez la coordination souffle-mouvement." },
  { id: "pivot-simple", name: "Pivot simple", category: "combat", difficulty: 1,
    description: "Depuis la garde, pivotez sur l'appui avant pour changer d'angle, sans frapper, à vitesse modérée." },
  { id: "mobilite-epaules-garde", name: "Mobilité épaules en garde", category: "combat", difficulty: 1,
    description: "En garde, effectuez de petits cercles avec les épaules pour les préparer sans lancer de frappe." },

  { id: "jab-cross", name: "Jab-cross (shadow boxing)", category: "combat", difficulty: 2,
    description: "Garde haute, enchîânez jab puis cross, revenez en garde à chaque fois." },
  { id: "footwork-boxe", name: "Déplacements de boxe", category: "combat", difficulty: 2,
    description: "En garde, déplacez-vous en petits pas avant/arrière/latéraux." },
  { id: "combo-crochets", name: "Combo crochets", category: "combat", difficulty: 2,
    description: "Enchîânez jab, cross puis crochet en pivotant sur l'appui." },
  { id: "teep", name: "Teep (coup de pied direct)", category: "combat", difficulty: 2,
    description: "Montez le genou puis poussez le pied vers l'avant en extension." },
  { id: "coups-de-genou", name: "Coups de genou", category: "combat", difficulty: 2,
    description: "Montez un genou fort vers le centre en alternant les jambes." },
  { id: "coups-de-coude", name: "Coups de coude", category: "combat", difficulty: 2,
    description: "Pivotez hanches et buste pour lancer des coups de coude horizontaux." },
  { id: "position-cavalier", name: "Position du cavalier", category: "combat", difficulty: 3,
    description: "Pieds très écartés, descendez comme assis sur une chaise, dos droit." },
  { id: "coup-de-pied-frontal", name: "Coup de pied frontal", category: "combat", difficulty: 2,
    description: "Chambrez le genou puis détendez la jambe en frappant vers l'avant." },
  { id: "frappe-paume", name: "Frappe de paume", category: "combat", difficulty: 2,
    description: "Projetez une paume vers l'avant en extension complète du bras." },
  { id: "esquive-retrait", name: "Esquive et retrait défensif", category: "combat", difficulty: 2,
    description: "Reculez d'un grand pas en montant les mains en garde défensive." },
  { id: "defense-360", name: "Défense 360°", category: "combat", difficulty: 2,
    description: "Balayez les avant-bras en cercle autour de vous en pivotant." },
  { id: "hip-escape", name: "Hip escape (esquive au sol)", category: "combat", difficulty: 2,
    description: "Allongé, poussez sur pied et épaule pour faire glisser les hanches en arrière." },

  // Combos multi-frappes
  { id: "combo-jab-jab-cross-elbow", name: "Combo jab-jab-cross-coude", category: "combat", difficulty: 3,
    description: "Enchîânez deux jabs rapides, un cross, puis un coup de coude croisé. Revenez en garde entre chaque frappe." },
  { id: "combo-kick-chain", name: "Enchîânement de coups de pied", category: "combat", difficulty: 4,
    description: "Enchîânez coup de pied avant, coup de pied arrière, coup de pied de côté arrière, puis un coup de pied retourné, en gardant l'équilibre entre chaque coup." },
  { id: "combo-roll-angle-hook", name: "Esquive, changement d'angle, crochet", category: "combat", difficulty: 3,
    description: "Esquivez en roulant le buste sous une frappe imaginaire, déplacez-vous en angle pour sortir de l'axe, puis ripostez d'un crochet de la main arrière." },
  { id: "combo-jab-cross-hook", name: "Combo jab-cross-crochet", category: "combat", difficulty: 3,
    description: "Enchîânez jab, cross puis crochet de la main avant, en pivotant sur l'appui à chaque frappe. Retour en garde systématique." },
  { id: "combo-low-kick-cross-hook", name: "Combo low kick-cross-crochet", category: "combat", difficulty: 4,
    description: "Frappez un coup de pied bas de la jambe arrière, puis enchîânez cross et crochet des mains sans reposer le pied entre les frappes." },
  { id: "combo-slip-cross-hook", name: "Esquive latérale-cross-crochet", category: "combat", difficulty: 3,
    description: "Esquivez latéralement une frappe imaginaire, puis contre-attaquez d'un cross suivi d'un crochet, menton rentré." },
  { id: "combo-knee-elbow", name: "Combo genou-coude", category: "combat", difficulty: 3,
    description: "Enchîânez un coup de genou puis un coup de coude du même côté, comme pour un corps à corps rapproché." },
  { id: "combo-double-jab-teep", name: "Combo double jab-teep", category: "combat", difficulty: 3,
    description: "Enchîânez deux jabs rapides puis un teep de la jambe arrière pour repousser la distance." },
  { id: "combo-parry-cross-hook-lowkick", name: "Pare-cross-crochet-low kick", category: "combat", difficulty: 4,
    description: "Parez une frappe imaginaire de la main avant, ripostez d'un cross puis d'un crochet, et terminez par un low kick de la jambe arrière." },
  { id: "combo-spinning-elbow", name: "Coude retourné (spinning elbow)", category: "combat", difficulty: 4,
    description: "Pivotez sur vous-même pour lancer un coup de coude retourné, équilibre sur l'appui avant, puis revenez en garde." },
  { id: "combo-sprawl-hook", name: "Défense de projection + riposte", category: "combat", difficulty: 4,
    description: "Simulez une défense de projection (hanches basses, jambes reculées), relevez-vous rapidement puis ripostez d'un crochet." },
  { id: "combo-triple-jab-cross", name: "Triple jab-cross", category: "combat", difficulty: 3,
    description: "Enchîânez trois jabs rapides puis un cross final, appuis légers et garde haute entre chaque frappe." },
  { id: "combo-jab-cross-genou", name: "Combo jab-cross-genou", category: "combat", difficulty: 3,
    description: "Enchîânez un jab, un cross, puis un coup de genou de la jambe arrière, retour en garde à chaque fois." },
  { id: "combo-teep-cross-hook", name: "Combo teep-cross-crochet", category: "combat", difficulty: 3,
    description: "Poussez un teep pour créer la distance, puis enchîânez immédiatement cross et crochet en avançant." },

  // Difficulté 4 (suite)
  { id: "combo-burpee-poings", name: "Burpee suivi d'un combo poings", category: "combat", difficulty: 4,
    description: "Enchîânez un burpee complet puis, en vous relevant, un jab-cross-crochet explosif." },
  { id: "combo-triple-kick", name: "Triple enchîânement de coups de pied", category: "combat", difficulty: 4,
    description: "Enchîânez trois coups de pied différents (frontal, latéral, circulaire) sur la même jambe sans reposer le pied entre chaque frappe." },
  { id: "combo-flurry", name: "Rafale de poings (flurry)", category: "combat", difficulty: 4,
    description: "Enchîânez le plus de jabs et crochets possible en 5 secondes à pleine vitesse, garde haute." },
  { id: "combo-superman-punch", name: "Superman punch", category: "combat", difficulty: 4,
    description: "Sautez légèrement en avant en tendant une jambe en arrière pour lancer un cross puissant, façon superman punch." },
  { id: "combo-coude-genou-explosif", name: "Coude-genou explosif", category: "combat", difficulty: 4,
    description: "Enchîânez un coup de coude puis un coup de genou du même côté à pleine intensité, sans pause entre les deux." },
];
