/**
 * Bibliothèque d'exercices sans équipement, répartis en 4 disciplines :
 * endurance, muscu, souplesse, combat. Chaque exercice dure 50 secondes
 * d'effort intense (voir app.js) — la description sert de rappel rapide
 * de la bonne exécution. `difficulty` va de 1 (facile) à 4 (très dur) et
 * sert à la fois pour la jauge affichée sur chaque exercice et pour le
 * score quotidien de l'écran Stats.
 */
const EXERCISES = [
  // ---------------------------------------------------------------------
  // ENDURANCE
  // ---------------------------------------------------------------------
  { id: "jumping-jacks", name: "Jumping jacks", category: "endurance", difficulty: 1,
    description: "Sautez en écartant bras et jambes, puis revenez en position de départ." },
  { id: "montees-genoux", name: "Montées de genoux", category: "endurance", difficulty: 2,
    description: "Courez sur place en montant les genoux le plus haut possible." },
  { id: "talons-fesses", name: "Talons-fesses", category: "endurance", difficulty: 1,
    description: "Courez sur place en amenant les talons vers les fessiers." },
  { id: "mountain-climbers", name: "Mountain climbers", category: "endurance", difficulty: 3,
    description: "En planche, ramenez rapidement les genoux vers la poitrine en alternant." },
  { id: "squats-sautes", name: "Squats sautés", category: "endurance", difficulty: 3,
    description: "Descendez en squat puis explosez vers le haut en sautant." },
  { id: "skaters", name: "Skaters", category: "endurance", difficulty: 3,
    description: "Sautez latéralement d'une jambe sur l'autre façon patineur." },
  { id: "star-jumps", name: "Star jumps", category: "endurance", difficulty: 2,
    description: "Accroupi, sautez en ouvrant bras et jambes en étoile." },
  { id: "corde-a-sauter", name: "Corde à sauter imaginaire", category: "endurance", difficulty: 2,
    description: "Petits sauts rapides sur place en mimant une corde à sauter." },
  { id: "burpees", name: "Burpees", category: "endurance", difficulty: 4,
    description: "Planche, pompe, ramenez les pieds, puis sautez bras tendus vers le ciel." },
  { id: "deplacements-lateraux", name: "Déplacements latéraux", category: "endurance", difficulty: 2,
    description: "Pas chassés rapides de gauche à droite en position basse." },
  { id: "sprint-sur-place", name: "Sprint sur place", category: "endurance", difficulty: 3,
    description: "Courez sur place le plus vite possible, petits appuis rapides." },
  { id: "fentes-sautees", name: "Fentes sautées", category: "endurance", difficulty: 3,
    description: "Alternez les jambes en fente avec un saut à chaque changement." },

  // ---------------------------------------------------------------------
  // MUSCU
  // ---------------------------------------------------------------------
  { id: "pompes", name: "Pompes", category: "muscu", difficulty: 2,
    description: "Corps aligné, descendez coudes à 45°, puis repoussez le sol." },
  { id: "pompes-diamant", name: "Pompes diamant", category: "muscu", difficulty: 3,
    description: "Mains sous la poitrine en losange, focus triceps." },
  { id: "pompes-piquees", name: "Pompes piquées", category: "muscu", difficulty: 3,
    description: "Fessiers en l'air en V inversé, pliez les coudes vers le sol." },
  { id: "gainage-planche", name: "Gainage planche", category: "muscu", difficulty: 2,
    description: "Appui avant-bras, corps aligné tête-bassin-talons, gainé." },
  { id: "gainage-lateral", name: "Gainage latéral", category: "muscu", difficulty: 2,
    description: "Sur le côté, appui avant-bras, corps aligné, hanche haute." },
  { id: "squats", name: "Squats", category: "muscu", difficulty: 1,
    description: "Pieds largeur bassin, descendez cuisses parallèles au sol." },
  { id: "fentes-avant", name: "Fentes avant", category: "muscu", difficulty: 2,
    description: "Alternez les jambes en fente, genou arrière proche du sol." },
  { id: "superman", name: "Superman", category: "muscu", difficulty: 1,
    description: "Au sol sur le ventre, soulevez bras et jambes simultanément." },
  { id: "crunchs-velo", name: "Crunchs vélo", category: "muscu", difficulty: 2,
    description: "Coude vers le genou opposé en alternant, comme un pédalage." },
  { id: "russian-twists", name: "Russian twists", category: "muscu", difficulty: 2,
    description: "Assis, buste incliné, tournez le buste de chaque côté." },
  { id: "v-ups", name: "V-ups", category: "muscu", difficulty: 3,
    description: "Allongé, levez jambes et buste ensemble pour former un V." },
  { id: "chaise", name: "Chaise", category: "muscu", difficulty: 2,
    description: "Dos au mur, cuisses parallèles au sol, maintenez la position." },
  { id: "hip-thrust", name: "Hip thrust au sol", category: "muscu", difficulty: 1,
    description: "Allongé, genoux pliés, poussez le bassin vers le haut." },
  { id: "dips-triceps", name: "Dips triceps au sol", category: "muscu", difficulty: 2,
    description: "Mains au sol derrière vous, pliez les coudes pour descendre le bassin." },

  // ---------------------------------------------------------------------
  // SOUPLESSE
  // ---------------------------------------------------------------------
  { id: "etirement-ischios", name: "Étirement des ischio-jambiers", category: "souplesse", difficulty: 1,
    description: "Jambe tendue devant, penchez le buste vers l'avant, dos droit." },
  { id: "flexion-avant", name: "Flexion assise vers l'avant", category: "souplesse", difficulty: 1,
    description: "Assis jambes tendues, basculez le buste vers l'avant depuis les hanches." },
  { id: "etirement-papillon", name: "Étirement papillon", category: "souplesse", difficulty: 1,
    description: "Assis, plantes de pieds jointes, appuyez doucement les genoux vers le sol." },
  { id: "posture-enfant", name: "Posture de l'enfant", category: "souplesse", difficulty: 1,
    description: "À genoux, asseyez-vous sur les talons, bras tendus devant vous." },
  { id: "chat-vache", name: "Chat-vache", category: "souplesse", difficulty: 1,
    description: "À quatre pattes, alternez dos creusé et dos arrondi au rythme du souffle." },
  { id: "chien-tete-en-bas", name: "Chien tête en bas", category: "souplesse", difficulty: 2,
    description: "Hanches vers le haut et l'arrière, formez un V inversé, talons vers le sol." },
  { id: "etirement-hanche", name: "Étirement fléchisseur de hanche", category: "souplesse", difficulty: 1,
    description: "En fente basse, poussez doucement le bassin vers l'avant." },
  { id: "etirement-quadriceps", name: "Étirement des quadriceps", category: "souplesse", difficulty: 2,
    description: "Debout, ramenez un talon vers la fesse en tenant la cheville." },
  { id: "etirement-fessier", name: "Étirement fessier (figure 4)", category: "souplesse", difficulty: 1,
    description: "Allongé, cheville croisée sur le genou opposé, tirez la cuisse vers vous." },
  { id: "etirement-cobra", name: "Étirement cobra", category: "souplesse", difficulty: 1,
    description: "Allongé sur le ventre, poussez le buste vers le haut, bassin au sol." },
  { id: "genou-poitrine", name: "Genou vers la poitrine", category: "souplesse", difficulty: 1,
    description: "Allongé, ramenez un genou vers la poitrine avec les deux mains." },
  { id: "torsion-assise", name: "Torsion du buste assise", category: "souplesse", difficulty: 1,
    description: "Assis, tournez le buste d'un côté en gardant le dos droit." },
  { id: "etirement-epaules", name: "Étirement épaules et triceps", category: "souplesse", difficulty: 1,
    description: "Bras au-dessus de la tête, coude plié, tirez doucement derrière la nuque." },

  // Adducteurs
  { id: "etirement-grenouille", name: "Étirement grenouille", category: "souplesse", difficulty: 2,
    description: "À quatre pattes, écartez largement les genoux, chevilles alignées avec les genoux. Reculez doucement le bassin vers les talons pour étirer l'intérieur des cuisses." },
  { id: "fente-laterale-cosaque", name: "Fente latérale (Cosaque)", category: "souplesse", difficulty: 3,
    description: "Jambes très écartées, pliez un genou en gardant l'autre jambe tendue, pied à plat. Basculez le poids d'un côté à l'autre pour étirer les adducteurs en dynamique." },
  { id: "grand-ecart-lateral", name: "Grand écart latéral progressif", category: "souplesse", difficulty: 4,
    description: "Jambes écartées au maximum de votre mobilité, mains au sol devant vous, laissez le bassin descendre progressivement pour approfondir l'étirement des adducteurs." },

  // Déplacements animaliers
  { id: "deplacement-ours", name: "Déplacement de l'ours", category: "souplesse", difficulty: 3,
    description: "À quatre pattes, genoux légèrement décollés du sol, avancez en faisant bouger la main et le pied opposés ensemble, dos plat et hanches basses." },
  { id: "deplacement-crabe", name: "Déplacement du crabe", category: "souplesse", difficulty: 3,
    description: "Assis, mains derrière vous, bassin décollé du sol. Déplacez-vous sur les mains et les pieds en gardant les hanches hautes et le dos droit." },
  { id: "deplacement-canard", name: "Déplacement du canard", category: "souplesse", difficulty: 3,
    description: "Descendez en squat profond, talons au sol si possible, et avancez à petits pas en restant bas, genoux vers l'extérieur." },
  { id: "deplacement-lezard", name: "Déplacement du lézard", category: "souplesse", difficulty: 3,
    description: "En fente basse très ouverte, mains au sol à l'intérieur du pied avant, avancez en alternant les côtés comme un lézard qui rampe, hanches proches du sol." },
  { id: "la-chenille", name: "La chenille", category: "souplesse", difficulty: 2,
    description: "Debout, pliez le buste et posez les mains au sol, marchez avec les mains vers l'avant jusqu'à la planche, puis ramenez les pieds vers les mains jambes tendues." },

  // Postures de yoga
  { id: "yoga-guerrier-2", name: "Posture du guerrier II", category: "souplesse", difficulty: 2,
    description: "Jambes écartées, genou avant plié à 90°, bras tendus à l'horizontale. Regard vers la main avant, hanches ouvertes sur le côté, maintenez la position." },
  { id: "yoga-arbre", name: "Posture de l'arbre", category: "souplesse", difficulty: 2,
    description: "En équilibre sur une jambe, posez le pied opposé contre la cheville, le mollet ou la cuisse (jamais sur le genou), mains jointes devant la poitrine." },
  { id: "yoga-pigeon", name: "Posture du pigeon", category: "souplesse", difficulty: 3,
    description: "Genou avant plié devant vous, tibia proche de l'horizontale, jambe arrière tendue derrière. Penchez le buste vers l'avant pour approfondir l'ouverture de hanche." },
  { id: "yoga-pince-debout", name: "Pince debout", category: "souplesse", difficulty: 1,
    description: "Debout, jambes tendues ou légèrement fléchies, laissez le buste tomber vers l'avant, tête relâchée, mains vers le sol ou les tibias." },
  { id: "yoga-corbeau", name: "Posture du corbeau", category: "souplesse", difficulty: 4,
    description: "Accroupi, mains au sol largeur épaules, posez les genoux sur l'arrière des bras et penchez le poids vers l'avant pour décoller les pieds du sol." },
  { id: "yoga-demi-lune", name: "Posture de la demi-lune", category: "souplesse", difficulty: 4,
    description: "En équilibre sur une jambe et une main au sol, levez l'autre jambe et l'autre bras à l'horizontale, corps aligné comme un T." },
  { id: "yoga-charrue", name: "Posture de la charrue", category: "souplesse", difficulty: 3,
    description: "Allongé sur le dos, levez les jambes puis les hanches pour amener les pieds au sol derrière la tête, mains au sol ou soutenant le bas du dos." },

  // Étirements dynamiques
  { id: "balancers-jambe", name: "Balancers de jambe dynamiques", category: "souplesse", difficulty: 2,
    description: "Debout en appui sur un support, balancez une jambe tendue d'avant en arrière puis latéralement, amplitude progressive." },

  // ---------------------------------------------------------------------
  // COMBAT
  // ---------------------------------------------------------------------
  { id: "jab-cross", name: "Jab-cross (shadow boxing)", category: "combat", difficulty: 2,
    description: "Garde haute, enchaînez jab puis cross, revenez en garde à chaque fois." },
  { id: "footwork-boxe", name: "Déplacements de boxe", category: "combat", difficulty: 2,
    description: "En garde, déplacez-vous en petits pas avant/arrière/latéraux." },
  { id: "combo-crochets", name: "Combo crochets", category: "combat", difficulty: 2,
    description: "Enchaînez jab, cross puis crochet en pivotant sur l'appui." },
  { id: "teep", name: "Teep (coup de pied direct)", category: "combat", difficulty: 2,
    description: "Montez le genou puis poussez le pied vers l'avant en extension." },
  { id: "coups-de-genou", name: "Coups de genou", category: "combat", difficulty: 2,
    description: "Montez un genou fort vers le centre en alternant les jambes." },
  { id: "coups-de-coude", name: "Coups de coude", category: "combat", difficulty: 2,
    description: "Pivotez hanches et buste pour lancer des coups de coude horizontaux." },
  { id: "position-cavalier", name: "Position du cavalier", category: "combat", difficulty: 3,
    description: "Pieds très écartés, descendez comme assis sur une chaise, dos droit." },
  { id: "coup-de-pied-frontal", name: "Coup de pied frontal", category: "combat", difficulty: 2,
    description: "Chambrez le genou puis détendez la jambe en frappant vers l'avant." },
  { id: "frappe-paume", name: "Frappe de paume", category: "combat", difficulty: 2,
    description: "Projetez une paume vers l'avant en extension complète du bras." },
  { id: "esquive-retrait", name: "Esquive et retrait défensif", category: "combat", difficulty: 2,
    description: "Reculez d'un grand pas en montant les mains en garde défensive." },
  { id: "defense-360", name: "Défense 360°", category: "combat", difficulty: 2,
    description: "Balayez les avant-bras en cercle autour de vous en pivotant." },
  { id: "hip-escape", name: "Hip escape (esquive au sol)", category: "combat", difficulty: 2,
    description: "Allongé, poussez sur pied et épaule pour faire glisser les hanches en arrière." },

  // Combos multi-frappes
  { id: "combo-jab-jab-cross-elbow", name: "Combo jab-jab-cross-coude", category: "combat", difficulty: 3,
    description: "Enchaînez deux jabs rapides, un cross, puis un coup de coude croisé. Revenez en garde entre chaque frappe." },
  { id: "combo-kick-chain", name: "Enchaînement de coups de pied", category: "combat", difficulty: 4,
    description: "Enchaînez coup de pied avant, coup de pied arrière, coup de pied de côté arrière, puis un coup de pied retourné, en gardant l'équilibre entre chaque coup." },
  { id: "combo-roll-angle-hook", name: "Esquive, changement d'angle, crochet", category: "combat", difficulty: 3,
    description: "Esquivez en roulant le buste sous une frappe imaginaire, déplacez-vous en angle pour sortir de l'axe, puis ripostez d'un crochet de la main arrière." },
  { id: "combo-jab-cross-hook", name: "Combo jab-cross-crochet", category: "combat", difficulty: 3,
    description: "Enchaînez jab, cross puis crochet de la main avant, en pivotant sur l'appui à chaque frappe. Retour en garde systématique." },
  { id: "combo-low-kick-cross-hook", name: "Combo low kick-cross-crochet", category: "combat", difficulty: 4,
    description: "Frappez un coup de pied bas de la jambe arrière, puis enchaînez cross et crochet des mains sans reposer le pied entre les frappes." },
  { id: "combo-slip-cross-hook", name: "Esquive latérale-cross-crochet", category: "combat", difficulty: 3,
    description: "Esquivez latéralement une frappe imaginaire, puis contre-attaquez d'un cross suivi d'un crochet, menton rentré." },
  { id: "combo-knee-elbow", name: "Combo genou-coude", category: "combat", difficulty: 3,
    description: "Enchaînez un coup de genou puis un coup de coude du même côté, comme pour un corps à corps rapproché." },
  { id: "combo-double-jab-teep", name: "Combo double jab-teep", category: "combat", difficulty: 3,
    description: "Enchaînez deux jabs rapides puis un teep de la jambe arrière pour repousser la distance." },
  { id: "combo-parry-cross-hook-lowkick", name: "Pare-cross-crochet-low kick", category: "combat", difficulty: 4,
    description: "Parez une frappe imaginaire de la main avant, ripostez d'un cross puis d'un crochet, et terminez par un low kick de la jambe arrière." },
  { id: "combo-spinning-elbow", name: "Coude retourné (spinning elbow)", category: "combat", difficulty: 4,
    description: "Pivotez sur vous-même pour lancer un coup de coude retourné, équilibre sur l'appui avant, puis revenez en garde." },
  { id: "combo-sprawl-hook", name: "Défense de projection + riposte", category: "combat", difficulty: 4,
    description: "Simulez une défense de projection (hanches basses, jambes reculées), relevez-vous rapidement puis ripostez d'un crochet." },
  { id: "combo-triple-jab-cross", name: "Triple jab-cross", category: "combat", difficulty: 3,
    description: "Enchaînez trois jabs rapides puis un cross final, appuis légers et garde haute entre chaque frappe." },
];
