/**
 * Bibliothèque d'exercices sans équipement, répartis en 4 disciplines :
 * endurance, muscu, souplesse, combat. Chaque exercice dure 50 secondes
 * d'effort intense (voir app.js) — la description sert de rappel rapide
 * de la bonne exécution.
 */
const EXERCISES = [
  // ---------------------------------------------------------------------
  // ENDURANCE
  // ---------------------------------------------------------------------
  { id: "jumping-jacks", name: "Jumping jacks", category: "endurance",
    description: "Sautez en écartant bras et jambes, puis revenez en position de départ." },
  { id: "montees-genoux", name: "Montées de genoux", category: "endurance",
    description: "Courez sur place en montant les genoux le plus haut possible." },
  { id: "talons-fesses", name: "Talons-fesses", category: "endurance",
    description: "Courez sur place en amenant les talons vers les fessiers." },
  { id: "mountain-climbers", name: "Mountain climbers", category: "endurance",
    description: "En planche, ramenez rapidement les genoux vers la poitrine en alternant." },
  { id: "squats-sautes", name: "Squats sautés", category: "endurance",
    description: "Descendez en squat puis explosez vers le haut en sautant." },
  { id: "skaters", name: "Skaters", category: "endurance",
    description: "Sautez latéralement d'une jambe sur l'autre façon patineur." },
  { id: "star-jumps", name: "Star jumps", category: "endurance",
    description: "Accroupi, sautez en ouvrant bras et jambes en étoile." },
  { id: "corde-a-sauter", name: "Corde à sauter imaginaire", category: "endurance",
    description: "Petits sauts rapides sur place en mimant une corde à sauter." },
  { id: "burpees", name: "Burpees", category: "endurance",
    description: "Planche, pompe, ramenez les pieds, puis sautez bras tendus vers le ciel." },
  { id: "deplacements-lateraux", name: "Déplacements latéraux", category: "endurance",
    description: "Pas chassés rapides de gauche à droite en position basse." },
  { id: "sprint-sur-place", name: "Sprint sur place", category: "endurance",
    description: "Courez sur place le plus vite possible, petits appuis rapides." },
  { id: "fentes-sautees", name: "Fentes sautées", category: "endurance",
    description: "Alternez les jambes en fente avec un saut à chaque changement." },

  // ---------------------------------------------------------------------
  // MUSCU
  // ---------------------------------------------------------------------
  { id: "pompes", name: "Pompes", category: "muscu",
    description: "Corps aligné, descendez coudes à 45°, puis repoussez le sol." },
  { id: "pompes-diamant", name: "Pompes diamant", category: "muscu",
    description: "Mains sous la poitrine en losange, focus triceps." },
  { id: "pompes-piquees", name: "Pompes piquées", category: "muscu",
    description: "Fessiers en l'air en V inversé, pliez les coudes vers le sol." },
  { id: "gainage-planche", name: "Gainage planche", category: "muscu",
    description: "Appui avant-bras, corps aligné tête-bassin-talons, gainé." },
  { id: "gainage-lateral", name: "Gainage latéral", category: "muscu",
    description: "Sur le côté, appui avant-bras, corps aligné, hanche haute." },
  { id: "squats", name: "Squats", category: "muscu",
    description: "Pieds largeur bassin, descendez cuisses parallèles au sol." },
  { id: "fentes-avant", name: "Fentes avant", category: "muscu",
    description: "Alternez les jambes en fente, genou arrière proche du sol." },
  { id: "superman", name: "Superman", category: "muscu",
    description: "Au sol sur le ventre, soulevez bras et jambes simultanément." },
  { id: "crunchs-velo", name: "Crunchs vélo", category: "muscu",
    description: "Coude vers le genou opposé en alternant, comme un pédalage." },
  { id: "russian-twists", name: "Russian twists", category: "muscu",
    description: "Assis, buste incliné, tournez le buste de chaque côté." },
  { id: "v-ups", name: "V-ups", category: "muscu",
    description: "Allongé, levez jambes et buste ensemble pour former un V." },
  { id: "chaise", name: "Chaise", category: "muscu",
    description: "Dos au mur, cuisses parallèles au sol, maintenez la position." },
  { id: "hip-thrust", name: "Hip thrust au sol", category: "muscu",
    description: "Allongé, genoux pliés, poussez le bassin vers le haut." },
  { id: "dips-triceps", name: "Dips triceps au sol", category: "muscu",
    description: "Mains au sol derrière vous, pliez les coudes pour descendre le bassin." },

  // ---------------------------------------------------------------------
  // SOUPLESSE
  // ---------------------------------------------------------------------
  { id: "etirement-ischios", name: "Étirement des ischio-jambiers", category: "souplesse",
    description: "Jambe tendue devant, penchez le buste vers l'avant, dos droit." },
  { id: "flexion-avant", name: "Flexion assise vers l'avant", category: "souplesse",
    description: "Assis jambes tendues, basculez le buste vers l'avant depuis les hanches." },
  { id: "etirement-papillon", name: "Étirement papillon", category: "souplesse",
    description: "Assis, plantes de pieds jointes, appuyez doucement les genoux vers le sol." },
  { id: "posture-enfant", name: "Posture de l'enfant", category: "souplesse",
    description: "À genoux, asseyez-vous sur les talons, bras tendus devant vous." },
  { id: "chat-vache", name: "Chat-vache", category: "souplesse",
    description: "À quatre pattes, alternez dos creusé et dos arrondi au rythme du souffle." },
  { id: "chien-tete-en-bas", name: "Chien tête en bas", category: "souplesse",
    description: "Hanches vers le haut et l'arrière, formez un V inversé, talons vers le sol." },
  { id: "etirement-hanche", name: "Étirement fléchisseur de hanche", category: "souplesse",
    description: "En fente basse, poussez doucement le bassin vers l'avant." },
  { id: "etirement-quadriceps", name: "Étirement des quadriceps", category: "souplesse",
    description: "Debout, ramenez un talon vers la fesse en tenant la cheville." },
  { id: "etirement-fessier", name: "Étirement fessier (figure 4)", category: "souplesse",
    description: "Allongé, cheville croisée sur le genou opposé, tirez la cuisse vers vous." },
  { id: "etirement-cobra", name: "Étirement cobra", category: "souplesse",
    description: "Allongé sur le ventre, poussez le buste vers le haut, bassin au sol." },
  { id: "genou-poitrine", name: "Genou vers la poitrine", category: "souplesse",
    description: "Allongé, ramenez un genou vers la poitrine avec les deux mains." },
  { id: "torsion-assise", name: "Torsion du buste assise", category: "souplesse",
    description: "Assis, tournez le buste d'un côté en gardant le dos droit." },
  { id: "etirement-epaules", name: "Étirement épaules et triceps", category: "souplesse",
    description: "Bras au-dessus de la tête, coude plié, tirez doucement derrière la nuque." },

  // ---------------------------------------------------------------------
  // COMBAT
  // ---------------------------------------------------------------------
  { id: "jab-cross", name: "Jab-cross (shadow boxing)", category: "combat",
    description: "Garde haute, enchaînez jab puis cross, revenez en garde à chaque fois." },
  { id: "footwork-boxe", name: "Déplacements de boxe", category: "combat",
    description: "En garde, déplacez-vous en petits pas avant/arrière/latéraux." },
  { id: "combo-crochets", name: "Combo crochets", category: "combat",
    description: "Enchaînez jab, cross puis crochet en pivotant sur l'appui." },
  { id: "teep", name: "Teep (coup de pied direct)", category: "combat",
    description: "Montez le genou puis poussez le pied vers l'avant en extension." },
  { id: "coups-de-genou", name: "Coups de genou", category: "combat",
    description: "Montez un genou fort vers le centre en alternant les jambes." },
  { id: "coups-de-coude", name: "Coups de coude", category: "combat",
    description: "Pivotez hanches et buste pour lancer des coups de coude horizontaux." },
  { id: "position-cavalier", name: "Position du cavalier", category: "combat",
    description: "Pieds très écartés, descendez comme assis sur une chaise, dos droit." },
  { id: "coup-de-pied-frontal", name: "Coup de pied frontal", category: "combat",
    description: "Chambrez le genou puis détendez la jambe en frappant vers l'avant." },
  { id: "frappe-paume", name: "Frappe de paume", category: "combat",
    description: "Projetez une paume vers l'avant en extension complète du bras." },
  { id: "esquive-retrait", name: "Esquive et retrait défensif", category: "combat",
    description: "Reculez d'un grand pas en montant les mains en garde défensive." },
  { id: "defense-360", name: "Défense 360°", category: "combat",
    description: "Balayez les avant-bras en cercle autour de vous en pivotant." },
  { id: "hip-escape", name: "Hip escape (esquive au sol)", category: "combat",
    description: "Allongé, poussez sur pied et épaule pour faire glisser les hanches en arrière." },
];
